// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfszbhurbdhpkrcsxeto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmc3piaHVyYmRocGtyY3N4ZXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDUxMTcsImV4cCI6MjA2Njk4MTExN30.CwdPu5iQqSwQGsW06lIGISYu7quNq8DSEZokBU8OjUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});